### ISSUE TITLE
FLOPs and Params

### ISSUE THREAD

**Issue by zlw1113** [yjsunnn/FBANet#3]
Could tou tell me the FLOPs and Params of FBANet?Thanks!

**Comment by yjsunnn** [comment]
Of course. The comparison result in the figure below is based on FBANet-S (dimension=32), different from the published FBANet-L (dimension=64). But through our experiment, the FBANet-S can still outperform SOTA models and achieve a competent performance with the FBANet-L (~0.1-0.2dB PSNR drop).
![image](https://github.com/yjsunnn/FBANet/assets/54736521/09c1a9b2-28a5-4b46-b7c4-f9ff45d88e92)
