### ISSUE TITLE
RealBSR-Raw

### ISSUE THREAD

**Issue by jamesli1618** [yjsunnn/FBANet#5]
Hi,
I found that you only released the RealBSR-RGB data. Do you plan to release the RealBSR-Raw dataset? Thanks.

**Comment by yjsunnn** [comment]
Here is a temporary link for both RGB and RAW dataset. [https://drive.google.com/drive/folders/1d4FOmRs0cKxWLPCsH-x7apVfsRJMKSJ4?usp=sharing](url) We are still trying our best to provide a more polished version. :)
