### ISSUE TITLE
Uncropped data

### ISSUE THREAD

**Issue by Hiuyee124** [yjsunnn/FBANet#9]
hi,I am very grateful for you sharing your data. However, when using the data, I found that it has already been cropped. May I ask if you can provide me with uncropped data?  Thank you very much.

**Comment by yjsunnn** [comment]
Sure, we will upload the uncropped RGB data to the drive link in a few days.

**Comment by yjsunnn** [comment]
Hi, we have updated the Readme.md and add the full-size RGB link in it. Or you can directly check the following link: https://pan.baidu.com/s/1ak1pWL8vnym6txisxksgdg?pwd=mr3m.

**Comment by Hiuyee124** [comment]
Thank you! It's really kind of you!
